### ISSUE TITLE
ModuleNotFoundError: No module named 'xontrib_commands'

### ISSUE THREAD

**Issue by rpdelaney** [jnoortheen/xontrib-commands#3]
Using 0.3.1:
```
Traceback (most recent call last):
  File "/home/ryan/.local/pipx/venvs/xonsh/lib/python3.10/site-packages/xonsh/__amalgam__.py", line 12116, in xontribs_load
    update_context(name, ctx=ctx)
  File "/home/ryan/.local/pipx/venvs/xonsh/lib/python3.10/site-packages/xonsh/__amalgam__.py", line 12072, in update_context
    modctx = xontrib_context(name)
  File "/home/ryan/.local/pipx/venvs/xonsh/lib/python3.10/site-packages/xonsh/__amalgam__.py", line 12037, in xontrib_context
    m = importlib.import_module(spec.name)
  File "/usr/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/ryan/.local/pipx/venvs/xonsh/lib/python3.10/site-packages/xontrib/commands.py", line 1, in <module>
    from xontrib_commands.utils import Command
ModuleNotFoundError: No module named 'xontrib_commands'
```
Reverting to 0.3.0 fixes the problem.

**Comment by jnoortheen** [comment]
Thanks for reporting. I just released a version - 0.3.2 with the fix .
